from sqlalchemy import text

from app.db import SessionLocal
from app.schemas.profile import StructuredProfile


class ProfileRepository:
    def save_structured_profile(
        self,
        *,
        user_id: str,
        cv_upload_id: str | None,
        structured_profile: StructuredProfile,
    ) -> dict:
        payload = structured_profile.model_dump()

        with SessionLocal.begin() as session:
            profile_row = session.execute(
                text(
                    """
                    select current_profile_version
                    from public.profiles
                    where id = :user_id
                    for update
                    """
                ),
                {"user_id": user_id},
            ).mappings().first()

            if profile_row is None:
                raise ValueError(f"Profile not found for user_id={user_id}")

            next_version = int(profile_row["current_profile_version"] or 0) + 1

            session.execute(
                text(
                    """
                    update public.profiles
                    set authoritative_profile = cast(:authoritative_profile as jsonb),
                        current_profile_version = :current_profile_version,
                        updated_at = now()
                    where id = :user_id
                    """
                ),
                {
                    "user_id": user_id,
                    "authoritative_profile": structured_profile.model_dump_json(),
                    "current_profile_version": next_version,
                },
            )

            session.execute(
                text(
                    """
                    insert into public.profile_versions (
                        user_id,
                        cv_upload_id,
                        version_no,
                        source,
                        snapshot,
                        validation_status,
                        change_note
                    )
                    values (
                        :user_id,
                        :cv_upload_id,
                        :version_no,
                        'ai_parse',
                        cast(:snapshot as jsonb),
                        'valid',
                        'Structured profile generated by CV processing scaffold.'
                    )
                    """
                ),
                {
                    "user_id": user_id,
                    "cv_upload_id": cv_upload_id,
                    "version_no": next_version,
                    "snapshot": structured_profile.model_dump_json(),
                },
            )

        return {
            "user_id": user_id,
            "cv_upload_id": cv_upload_id,
            "profile_saved": True,
            "version_created": True,
            "current_profile_version": next_version,
            "structured_profile": payload,
        }
